---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "front"
  namespace: "default"
  labels:
    app: "front"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "front"
  template:
    metadata:
      labels:
        app: "front"
    spec:
      containers:
      - name: "rouge"
        image: "nginx:latest"
      - name: "bleu"
        image: "nginx:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "front-hpa"
  namespace: "default"
  labels:
    app: "front"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "front"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
