---
apiVersion: "apps/v1"
kind: "deployment"
metadata:
  name: "front"
  namespace: "default"
  labels:
    app: "front"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "front"
  template:
    metadata: 
      labels:
        app: "front"
    spec:
      containers:
      - name: bleu
        image: eu.gcr.io/gke-discovery-03/stunnel:v1
        ports:
        - containerPort: 80

#      - name: rouge
#        image: eu.gcr.io/gke-discovery-03/rouge:v1
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
#        ports:
#        - containerPort: 80
