apiVersion: v1
kind: Pod
metadata:
    name: front
spec:
  containers:
  - name: rouge
    image: eu.gcr.io/gke-discovery-03/rouge:v1
    ports:
      - containerPort: 80

  - name: bleu
    image: eu.gcr.io/gke-discovery-03/bleu:v1
    ports:
      - containerPort: 8080
