apiVersion: v1
kind: Service
metadata:
  name: demo-node-front
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 38080
  selector:
    app: front
