apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "site-rouge"
  namespace: "default"
  labels:
    env: "back"
    app: "web"
spec:
  replicas: 1
  selector:
    matchLabels:
      env: "back"
      app: "web"
  template:
    metadata:
      labels:
        env: "back"
        app: "web"
    spec:
      containers:
      - name: site-rouge
        image: eu.gcr.io/gke-discovery-03/rouge:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.2
            memory: "10Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 81
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
