#kind: Service
#apiVersion: v1
#metadata:
#  name: lb-interne
#spec:
#  selector:
#    app: web
#  ports:
#    port: 80
#    targetPort: 80
#    protocol: TCP

kind: Service
apiVersion: v1
metadata:
  name: "lb-interne"
spec:
  selector:
    app: "web"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
