apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: site-bleu
  namespace: default
  labels:
    app: front
    track: stable
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
      track: stable
      version: 1.0.0
  template:
    metadata:
      labels:
        app: front
        track: stable
        version: 1.0.0
    spec:
      containers:
      - name: site-bleu
        image: eu.gcr.io/gke-discovery-03/bleu:v1
        ports:
        - containerPort: 80
#        resources:
#          limits:
#            cpu: 0.2
#            memory: "10Mi"
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 81
#            scheme: HTTP
#          initialDelaySeconds: 5
#          periodSeconds: 15
#          timeoutSeconds: 5

#      containers:
#      - name: site-bleu-v1
#        image: eu.gcr.io/gke-discovery-03/bleu:v1
#        ports:
#        - containerPort: 80
#          resources:
#            limits:
#              cpu: 0.2
#              memory: "10Mi"
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 81
#              scheme: HTTP
#            initialDelaySeconds: 5
#            periodSeconds: 15
#            timeoutSeconds: 5

#        livenessProbe:
#          initialDelaySeconds: 10
#          timeoutSeconds: 1
#          httpget:
#            path: /
#            port: 80






#apiVersion: "apps/v1"
#kind: "Deployment"
#metadata:
#  namespace: site-bleu
#spec:
#  replicas: 2
#  selector:
#    role: "bleu"
#  template:
#    metadata:
#      name: "bleu"
#      labels:
#        role: "bleu"
#    spec:
#      containers:
#      - name: "site-bleu-v1"
#        image: "eu.gcr.io/gke-discovery-03/bleu:v1"
#        ports:
#        - containerPort: 80
